# Generated by Django 3.1.3 on 2021-01-14 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wallet.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('symbol', models.CharField(max_length=3, unique=True, verbose_name='Symbol')),
                ('bid_usd', models.FloatField(blank=True, null=True, verbose_name='Bid USD')),
                ('icon', models.ImageField(blank=True, default='', upload_to=wallet.models.currency_icon_path, verbose_name='Icon')),
                ('is_crypto', models.BooleanField(default=False, verbose_name='Is crypto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active(can create active wallet)')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['bid_usd'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('balance', models.DecimalField(decimal_places=10, default=0, max_digits=19, verbose_name='Balance')),
                ('public_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Public Key')),
                ('private_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Private Key')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.currency', verbose_name='Currency')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
    ]
