# Generated by Django 3.1.3 on 2021-01-14 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wallet.currency', verbose_name='Currency'),
        ),
    ]
