# Generated by Django 3.1.3 on 2021-01-14 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0002_auto_20210114_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='address',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='private_key',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='public_key',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
