# Generated by Django 3.1.3 on 2021-02-21 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_wallet_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Balance'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('status', models.CharField(choices=[('initial', 'INITIAL'), ('denied', 'DENIED'), ('pending', 'PENDING'), ('success', 'SUCCESS'), ('cancelled', 'CANCELLED')], default='initial', max_length=25, verbose_name='Status')),
                ('from_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_send', to='wallet.wallet', verbose_name='From Wallet')),
                ('to_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_received', to='wallet.wallet', verbose_name='To wallet')),
            ],
            options={
                'verbose_name': ('Transaction',),
                'verbose_name_plural': ('Transactions',),
            },
        ),
    ]
