# Generated by Django 3.1.3 on 2021-03-07 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_auto_20210109_1524'),
        ('wallet', '0007_auto_20210307_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.item', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active (can create active wallet)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.currency', verbose_name='Currency'),
        ),
    ]
