# Generated by Django 3.1.3 on 2021-03-07 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_auto_20210307_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='to_wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_received', to='wallet.wallet', verbose_name='To wallet'),
        ),
    ]
