# Generated by Django 3.1.3 on 2020-12-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.IntegerField(choices=[(1, 'On sail'), (2, 'Sailed'), (3, 'Sold')], db_index=True, default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Title'),
        ),
    ]
