# Generated by Django 3.1.3 on 2020-12-16 07:54

from django.db import migrations, models
import django.db.models.deletion
import todo.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20201215_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AddField(
            model_name='item',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to=todo.models.house_photo_path, verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='item',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='todo.address'),
        ),
    ]
