# Generated by Django 3.1.3 on 2020-12-16 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20201216_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='todo.address'),
        ),
    ]
