# Generated by Django 3.1.3 on 2020-12-16 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20201216_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='todo.address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='house_number',
            field=models.CharField(max_length=25, verbose_name='House number'),
        ),
    ]
