# Generated by Django 3.1.3 on 2020-12-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_auto_20201217_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='title',
        ),
        migrations.AddField(
            model_name='item',
            name='house_type',
            field=models.IntegerField(choices=[(1, 'Cottage'), (2, 'Multistorey house')], db_index=True, default=1, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Zip code'),
        ),
    ]
