# Generated by Django 3.1.3 on 2021-03-08 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_auto_20210307_1147'),
        ('todo', '0013_auto_20210109_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.currency', verbose_name='Currency'),
        ),
    ]
