# Generated by Django 3.1.3 on 2020-12-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Consumer'), (2, 'Company')], db_index=True, default=2, verbose_name='Role'),
        ),
    ]
